### PR TITLE
Use in_path instead of cd to restore previous path

### PR DESCRIPTION
**Pull request by sobrinho**
See mina-deploy/mina#478.

### CODE REVIEW

**Comment by sobrinho** [comment]
Makes sense only after mina-deploy/mina#478 but nothing bad must happen before that.

I'm unable to run the test suit since it depends on some kind of local ssh running.

**Comment by devvmh** [comment]
Looks like it works on Travis, so no worries about the test suite

Can you post here when mina-deploy/mina#478  gets merged?

**Comment by sobrinho** [comment]
I believe you can merge this change before the mina release because nothing will change from the current behavior of mina-sidekiq.

But if you want to document this issue on changelog and quote, then will make sense.

In other words, if you decide to wait, I will keep you posted, otherwise you can just merge.

Thanks! ❤️

**Comment by sobrinho** [comment]
The pull request got merged on mina, not sure if they will release a new version soon.

**Comment by devvmh** [comment]
All right, looks good to me.

**Comment by Mic92** [comment]
I can create patch release.

**Comment by devvmh** [comment]
You're a trooper! 😂

**Comment by Mic92** [comment]
here we go: 1.0.1

**Comment by sobrinho** [comment]
Thanks guys! <3

**Pull request merged**
