### PR TITLE
Defaults sidekiq_concurrency to nil

### PR DESCRIPTION
**Pull request by linusramos**
* it overrides concurrency in config file

### CODE REVIEW

**Comment by Mic92** [comment]
could you instead set the default value to nil, and still pass the flag if it is unequal nil?

**Comment by linusramos** [comment]
Do you have any use for that parameter? Sidekiq defaults to 25 threads when you don't pass a concurrency value. :)

**Comment by Mic92** [comment]
I do not have any use for the library at all at the moment. That is why I am looking for a new maintainer.
But this an option, which users can override to set concurrency. As it is part of the documented api it is likely that some folks made use of it. So the sensible way to not break their deployment is to keep the option, but do not pass it by default to sidekiq.

**Comment by linusramos** [comment]
Ah! Now I understand why you want to keep it. Okay, will check how to retain it and send a pull request after.

**Pull request closed without merging**
